sudo: required

before_install:
 - sudo apt-get --assume-yes update
 - sudo apt-get --assume-yes install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev screen git nano
 - deb http://ftp.debian.org/debian jessie-backports main && apt-get update && apt-get -t jessie-backports install -y --no-install-recommends cmake && apt-get clean && rm -rf /var/lib/apt/lists/*
 - cd /usr/local/src/
 - sudo git clone https://github.com/Caboosium/cpu.git
 - cd cpu
 - sudo cmake .

install:
 - sudo make install

script:
 - cd bin/
 - sudo chmod +x *
 - sudo ls
 
